# Generated by Django 5.0.6 on 2024-10-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_sitevisitor_alter_master_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
