# Generated by Django 5.0.6 on 2024-10-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_sitevisitor_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitevisitor',
            old_name='visited_at',
            new_name='first_visited_at',
        ),
        migrations.AddField(
            model_name='sitevisitor',
            name='last_visited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
