# Generated by Django 5.0.6 on 2024-10-22 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_rename_visited_at_sitevisitor_first_visited_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisitor',
            options={'verbose_name': 'Запись клиента', 'verbose_name_plural': 'Записи клиентов'},
        ),
        migrations.AlterField(
            model_name='sitevisitor',
            name='first_visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время первого посещения'),
        ),
        migrations.AlterField(
            model_name='sitevisitor',
            name='last_visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последнего посещения'),
        ),
    ]
