# Generated by Django 5.0.6 on 2024-10-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_sitevisitor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisitor',
            options={'verbose_name': 'Посетитель сайта', 'verbose_name_plural': 'Посетители сайта'},
        ),
    ]
