# Generated by Django 5.0.6 on 2025-03-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_alter_sitevisitor_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteVisitor',
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-created_at',), 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='status',
        ),
    ]
