# Generated by Django 5.0.6 on 2025-03-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0007_delete_sitevisitor_alter_master_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="license",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="review",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cabinet.master"
            ),
        ),
    ]
